if(typeof Object.assign!='function'){Object.assign=function(target){'use strict';if(target==null){throw new TypeError('Cannot convert undefined or null to object');}
target=Object(target);for(var index=1;index<arguments.length;index++){var source=arguments[index];if(source!=null){for(var key in source){if(Object.prototype.hasOwnProperty.call(source,key)){target[key]=source[key];}}}}
return target;};}
(function(){if(!Function.prototype.bind){Function.prototype.bind=function(oThis){if(typeof this!=="function"){throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");}
var aArgs=Array.prototype.slice.call(arguments,1),fToBind=this,fNOP=function(){},fBound=function(){return fToBind.apply(this instanceof fNOP&&oThis?this:oThis,aArgs.concat(Array.prototype.slice.call(arguments)));};fNOP.prototype=this.prototype;fBound.prototype=new fNOP();return fBound;};}}());function BannerSlide(option){this._init(option);}
BannerSlide.prototype={_init:function(option){this.compatibleConsole();this.isThisAttr(option);this.container=option.container;this.imagesSrc=option.imagesSrc;this.switchEffect=Object.assign({},{slide:true,arrow:true,radius:true},option.switchEffect);this.speed=option.speed?option.speed:3000;this.bannerHtmlLoad();this.bindEvent();},isThisAttr:function(option){var msg=!option&&'未传入配置对象(new BannerSlide()未传入对象)'||(!option.container||option.container.constructor!==String)&&'无目标容器(container属性字符串值未传入)'||(!option.imagesSrc||option.imagesSrc.constructor!==Array)&&'无图片路径(imagesSrc属性数组值未传入)'||null;if(msg){throw new TypeError(msg+'————BannerSlide.js');}},compatibleConsole:function(){window.console=window.console||(function(){var c={};c.log=c.warn=c.debug=c.info=c.error=c.time=c.dir=c.profile=c.clear=c.exception=c.trace=c.assert=function(){};return c;})();},bannerHtmlLoad:function(){var str='<div class="bannerSlide-container" id="bannerSlide-container">\
                    <div class="bs-images">';for(var i=0 in this.imagesSrc){str+='<img '+(i==0?"class=' checked'":"")+' src="'+this.imagesSrc[i]+'" alt="">';}
str+='</div>';if(this.switchEffect.arrow){str+='<div class="bs-scope">\
                                <div class="left-btn"></div>\
                                <div class="right-btn"></div>\
                            </div>';}
if(this.switchEffect.radius){str+='<div class="bs-radius">';for(var i=0 in this.imagesSrc){str+='<span'+(i==0?" class='checked'":"")+'></span>';}}
str+='</div>\
            </div>';document.querySelector(this.container).innerHTML=str;},bindEvent:function(){this.doms={},this.index=1;this.doms=Object.assign({},{MaxBox:document.getElementById('bannerSlide-container'),images:document.querySelectorAll('#bannerSlide-container .bs-images>img'),leftBtn:document.querySelector('#bannerSlide-container .bs-scope .left-btn'),rightBtn:document.querySelector('#bannerSlide-container .bs-scope .right-btn'),radiusBtn:document.querySelectorAll('#bannerSlide-container .bs-radius>span')},this.doms);var _this=this;if(this.switchEffect.slide){this.time=setInterval(function(){this.slideFun();}.bind(this),this.speed);}
if(this.switchEffect.arrow){this.doms.leftBtn.onclick=function(){return this.clickIndex(-1);}.bind(_this);this.doms.rightBtn.onclick=function(){return this.clickIndex(1);}.bind(_this);}
if(this.switchEffect.radius){for(var i=0;i<this.doms.radiusBtn.length;i++){this.doms.radiusBtn[i].onclick=function(){_this.index=0;_this.clickIndex(_this.prevAllDom(this).length);}}}},slideFun:function(){this.render();this.index++;},clickIndex:function(num){clearInterval(this.time);this.time=null;this.index+=num;this.render();this.time=setInterval(function(){this.slideFun();}.bind(this),this.speed);},render:function(){if(this.index>this.doms.images.length-1){this.index=0;}else if(this.index<0){this.index=this.doms.images.length-1;}
for(var j=0;j<this.doms.images.length;j++){this.removeClass(this.doms.images[j],'checked');if(this.switchEffect.radius){this.removeClass(this.doms.radiusBtn[j],'checked');}}
if(this.switchEffect.radius){this.addClass(this.doms.radiusBtn[this.index],'checked');}
this.addClass(this.doms.images[this.index],'checked');},addClass:function(ele,cls){if(!this.hasClass(ele,cls)){ele.className=ele.className==''?cls:ele.className+' '+cls;}},removeClass:function(ele,cls){if(this.hasClass(ele,cls)){var newClass=' '+ele.className.replace(/[\t\r\n]/g,'')+' ';while(newClass.indexOf(' '+cls+' ')>=0){newClass=newClass.replace(' '+cls+' ',' ');}
ele.className=newClass.replace(/^\s+|\s+$/g,'');}},hasClass:function(ele,cls){cls=cls||'';if(cls.replace(/\s/g,'').length==0)return false;return new RegExp(' '+cls+' ').test(' '+ele.className+' ');},prevAllDom:function(obj){var pe=obj.parentElement;var cs=pe.children;var arr=[];for(var i=0;i<cs.length;i++){var csi=cs[i];if(csi==obj){break;}
arr.push(csi);}
return arr;}};